class countries {
  static Allcountries() {
    // const countries = [
    //     { value: 'AF', label: 'Afghanistan' },
    //     { value: 'AX', label: 'Åland Islands' },
    //     { value: 'AL', label: 'Albania' },
    //     { value: 'DZ', label: 'Algeria' },
    //     { value: 'AS', label: 'American Samoa' },
    //     { value: 'AD', label: 'Andorra' },
    //     { value: 'AO', label: 'Angola' },
    //     { value: 'AI', label: 'Anguilla' },
    //     { value: 'AQ', label: 'Antarctica' },
    //     { value: 'AG', label: 'Antigua and Barbuda' },
    //     { value: 'AR', label: 'Argentina' },
    //     { value: 'AM', label: 'Armenia' },
    //     { value: 'AW', label: 'Aruba' },
    //     { value: 'AU', label: 'Australia' },
    //     { value: 'AT', label: 'Austria' },
    //     { value: 'AZ', label: 'Azerbaijan' },
    //     { value: 'BS', label: 'Bahamas' },
    //     { value: 'BH', label: 'Bahrain' },
    //     { value: 'BD', label: 'Bangladesh' },
    //     { value: 'BB', label: 'Barbados' },
    //     { value: 'BY', label: 'Belarus' },
    //     { value: 'BE', label: 'Belgium' },
    //     { value: 'BZ', label: 'Belize' },
    //     { value: 'BJ', label: 'Benin' },
    //     { value: 'BM', label: 'Bermuda' },
    //     { value: 'BT', label: 'Bhutan' },
    //     { value: 'BO', label: 'Bolivia' },
    //     { value: 'BQ', label: 'Bonaire, Sint Eustatius and Saba' },
    //     { value: 'BA', label: 'Bosnia and Herzegovina' },
    //     { value: 'BW', label: 'Botswana' },
    //     { value: 'BV', label: 'Bouvet Island' },
    //     { value: 'BR', label: 'Brazil' },
    //     { value: 'IO', label: 'British Indian Ocean Territory' },
    //     { value: 'BN', label: 'Brunei Darussalam' },
    //     { value: 'BG', label: 'Bulgaria' },
    //     { value: 'BF', label: 'Burkina Faso' },
    //     { value: 'BI', label: 'Burundi' },
    //     { value: 'KH', label: 'Cambodia' },
    //     { value: 'CM', label: 'Cameroon' },
    //     { value: 'CA', label: 'Canada' },
    //     { value: 'CV', label: 'Cape Verde' },
    //     { value: 'KY', label: 'Cayman Islands' },
    //     { value: 'CF', label: 'Central African Republic' },
    //     { value: 'TD', label: 'Chad' },
    //     { value: 'CL', label: 'Chile' },
    //     { value: 'CN', label: 'China' },
    //     { value: 'CX', label: 'Christmas Island' },
    //     { value: 'CC', label: 'Cocos (Keeling) Islands' },
    //     { value: 'CO', label: 'Colombia' },
    //     { value: 'KM', label: 'Comoros' },
    //     { value: 'CG', label: 'Congo' },
    //     { value: 'CD', label: 'Congo, Democratic Republic of the' },
    //     { value: 'CK', label: 'Cook Islands' },
    //     { value: 'CR', label: 'Costa Rica' },
    //     { value: 'CI', label: 'Côte d\'Ivoire' },
    //     { value: 'HR', label: 'Croatia' },
    //     { value: 'CU', label: 'Cuba' },
    //     { value: 'CW', label: 'Curaçao' },
    //     { value: 'CY', label: 'Cyprus' },
    //     { value: 'CZ', label: 'Czech Republic' },
    //     { value: 'DK', label: 'Denmark' },
    //     { value: 'DJ', label: 'Djibouti' },
    //     { value: 'DM', label: 'Dominica' },
    //     { value: 'DO', label: 'Dominican Republic' },
    //     { value: 'EC', label: 'Ecuador' },
    //     { value: 'EG', label: 'Egypt' },
    //     { value: 'SV', label: 'El Salvador' },
    //     { value: 'GQ', label: 'Equatorial Guinea' },
    //     { value: 'ER', label: 'Eritrea' },
    //     { value: 'EE', label: 'Estonia' },
    //     { value: 'ET', label: 'Ethiopia' },
    //     { value: 'FK', label: 'Falkland Islands (Malvinas)' },
    //     { value: 'FO', label: 'Faroe Islands' },
    //     { value: 'FJ', label: 'Fiji' },
    //     { value: 'FI', label: 'Finland' },
    //     { value: 'FR', label: 'France' },
    //     { value: 'GF', label: 'French Guiana' },
    //     { value: 'PF', label: 'French Polynesia' },
    //     { value: 'TF', label: 'French Southern Territories' },
    //     { value: 'GA', label: 'Gabon' },
    //     { value: 'GM', label: 'Gambia' },
    //     { value: 'GE', label: 'Georgia' },
    //     { value: 'DE', label: 'Germany' },
    //     { value: 'GH', label: 'Ghana' },
    //     { value: 'GI', label: 'Gibraltar' },
    //     { value: 'GR', label: 'Greece' },
    //     { value: 'GL', label: 'Greenland' },
    //     { value: 'GD', label: 'Grenada' },
    //     { value: 'GP', label: 'Guadeloupe' },
    //     { value: 'GU', label: 'Guam' },
    //     { value: 'GT', label: 'Guatemala' },
    //     { value: 'GG', label: 'Guernsey' },
    //     { value: 'GN', label: 'Guinea' },
    //     { value: 'GW', label: 'Guinea-Bissau' },
    //     { value: 'GY', label: 'Guyana' },
    //     { value: 'HT', label: 'Haiti' },
    //     { value: 'HM', label: 'Heard Island and McDonald Islands' },
    //     { value: 'VA', label: 'Holy See (Vatican City State)' },
    //     { value: 'HN', label: 'Honduras' },
    //     { value: 'HK', label: 'Hong Kong' },
    //     { value: 'HU', label: 'Hungary' },
    //     { value: 'IS', label: 'Iceland' },
    //     { value: 'IN', label: 'India' },
    //     { value: 'ID', label: 'Indonesia' },
    //     { value: 'IR', label: 'Iran, Islamic Republic of' },
    //     { value: 'IQ', label: 'Iraq' },
    //     { value: 'IE', label: 'Ireland' },
    //     { value: 'IM', label: 'Isle of Man' },
    //     { value: 'IL', label: 'Israel' },
    //     { value: 'IT', label: 'Italy' },
    //     { value: 'JM', label: 'Jamaica' },
    //     { value: 'JP', label: 'Japan' },
    //     { value: 'JE', label: 'Jersey' },
    //     { value: 'JO', label: 'Jordan' },
    //     { value: 'KZ', label: 'Kazakhstan' },
    //     { value: 'KE', label: 'Kenya' },
    //     { value: 'KI', label: 'Kiribati' },
    //     { value: 'KP', label: 'Korea, Democratic People\'s Republic of' },
    //     { value: 'KR', label: 'Korea, Republic of' },
    //     { value: 'KW', label: 'Kuwait' },
    //     { value: 'KG', label: 'Kyrgyzstan' },
    //     { value: 'LA', label: 'Lao People\'s Democratic Republic' },
    //     { value: 'LV', label: 'Latvia' },
    //     { value: 'LB', label: 'Lebanon' },
    //     { value: 'LS', label: 'Lesotho' },
    //     { value: 'LR', label: 'Liberia' },
    //     { value: 'LY', label: 'Libya' },
    //     { value: 'LI', label: 'Liechtenstein' },
    //     { value: 'LT', label: 'Lithuania' },
    //     { value: 'LU', label: 'Luxembourg' },
    //     { value: 'MO', label: 'Macao' },
    //     { value: 'MK', label: 'Macedonia, the former Yugoslav Republic of' },
    //     { value: 'MG', label: 'Madagascar' },
    //     { value: 'MW', label: 'Malawi' },
    //     { value: 'MY', label: 'Malaysia' },
    //     { value: 'MV', label: 'Maldives' },
    //     { value: 'ML', label: 'Mali' },
    //     { value: 'MT', label: 'Malta' },
    //     { value: 'MH', label: 'Marshall Islands' },
    //     { value: 'MQ', label: 'Martinique' },
    //     { value: 'MR', label: 'Mauritania' },
    //     { value: 'MU', label: 'Mauritius' },
    //     { value: 'YT', label: 'Mayotte' },
    //     { value: 'MX', label: 'Mexico' },
    //     { value: 'FM', label: 'Micronesia, Federated States of' },
    //     { value: 'MD', label: 'Moldova, Republic of' },
    //     { value: 'MC', label: 'Monaco' },
    //     { value: 'MN', label: 'Mongolia' },
    //     { value: 'ME', label: 'Montenegro' },
    //     { value: 'MS', label: 'Montserrat' },
    //     { value: 'MA', label: 'Morocco' },
    //     { value: 'MZ', label: 'Mozambique' },
    //     { value: 'MM', label: 'Myanmar' },
    //     { value: 'NA', label: 'Namibia' },
    //     { value: 'NR', label: 'Nauru' },
    //     { value: 'NP', label: 'Nepal' },
    //     { value: 'NL', label: 'Netherlands' },
    //     { value: 'NC', label: 'New Caledonia' },
    //     { value: 'NZ', label: 'New Zealand' },
    //     { value: 'NI', label: 'Nicaragua' },
    //     { value: 'NE', label: 'Niger' },
    //     { value: 'NG', label: 'Nigeria' },
    //     { value: 'NU', label: 'Niue' },
    //     { value: 'NF', label: 'Norfolk Island' },
    //     { value: 'MP', label: 'Northern Mariana Islands' },
    //     { value: 'NO', label: 'Norway' },
    //     { value: 'OM', label: 'Oman' },
    //     { value: 'PK', label: 'Pakistan' },
    //     { value: 'PW', label: 'Palau' },
    //     { value: 'PS', label: 'Palestinian Territory, Occupied' },
    //     { value: 'PA', label: 'Panama' },
    //     { value: 'PG', label: 'Papua New Guinea' },
    //     { value: 'PY', label: 'Paraguay' },
    //     { value: 'PE', label: 'Peru' },
    //     { value: 'PH', label: 'Philippines' },
    //     { value: 'PN', label: 'Pitcairn' },
    //     { value: 'PL', label: 'Poland' },
    //     { value: 'PT', label: 'Portugal' },
    //     { value: 'PR', label: 'Puerto Rico' },
    //     { value: 'QA', label: 'Qatar' },
    //     { value: 'RE', label: 'Réunion' },
    //     { value: 'RO', label: 'Romania' },
    //     { value: 'RU', label: 'Russian Federation' },
    //     { value: 'RW', label: 'Rwanda' },
    //     { value: 'BL', label: 'Saint Barthélemy' },
    //     { value: 'SH', label: 'Saint Helena, Ascension and Tristan da Cunha' },
    //     { value: 'KN', label: 'Saint Kitts and Nevis' },
    //     { value: 'LC', label: 'Saint Lucia' },
    //     { value: 'MF', label: 'Saint Martin (French part)' },
    //     { value: 'PM', label: 'Saint Pierre and Miquelon' },
    //     { value: 'VC', label: 'Saint Vincent and the Grenadines' },
    //     { value: 'WS', label: 'Samoa' },
    //     { value: 'SM', label: 'San Marino' },
    //     { value: 'ST', label: 'Sao Tome and Principe' },
    //     { value: 'SA', label: 'Saudi Arabia' },
    //     { value: 'SN', label: 'Senegal' },
    //     { value: 'RS', label: 'Serbia' },
    //     { value: 'SC', label: 'Seychelles' },
    //     { value: 'SL', label: 'Sierra Leone' },
    //     { value: 'SG', label: 'Singapore' },
    //     { value: 'SX', label: 'Sint Maarten (Dutch part)' },
    //     { value: 'SK', label: 'Slovakia' },
    //     { value: 'SI', label: 'Slovenia' },
    //     { value: 'SB', label: 'Solomon Islands' },
    //     { value: 'SO', label: 'Somalia' },
    //     { value: 'ZA', label: 'South Africa' },
    //     { value: 'GS', label: 'South Georgia and the South Sandwich Islands' },
    //     { value: 'SS', label: 'South Sudan' },
    //     { value: 'ES', label: 'Spain' },
    //     { value: 'LK', label: 'Sri Lanka' },
    //     { value: 'SD', label: 'Sudan' },
    //     { value: 'SR', label: 'Suriname' },
    //     { value: 'SJ', label: 'Svalbard and Jan Mayen' },
    //     { value: 'SZ', label: 'Swaziland' },
    //     { value: 'SE', label: 'Sweden' },
    //     { value: 'CH', label: 'Switzerland' },
    //     { value: 'SY', label: 'Syrian Arab Republic' },
    //     { value: 'TW', label: 'Taiwan, Province of China' },
    //     { value: 'TJ', label: 'Tajikistan' },
    //     { value: 'TZ', label: 'Tanzania, United Republic of' },
    //     { value: 'TH', label: 'Thailand' },
    //     { value: 'TL', label: 'Timor-Leste' },
    //     { value: 'TG', label: 'Togo' },
    //     { value: 'TK', label: 'Tokelau' },
    //     { value: 'TO', label: 'Tonga' },
    //     { value: 'TT', label: 'Trinidad and Tobago' },
    //     { value: 'TN', label: 'Tunisia' },
    //     { value: 'TR', label: 'Turkey' },
    //     { value: 'TM', label: 'Turkmenistan' },
    //     { value: 'TC', label: 'Turks and Caicos Islands' },
    //     { value: 'TV', label: 'Tuvalu' },
    //     { value: 'UG', label: 'Uganda' },
    //     { value: 'UA', label: 'Ukraine' },
    //     { value: 'AE', label: 'United Arab Emirates' },
    //     { value: 'GB', label: 'United Kingdom' },
    //     { value: 'US', label: 'United States' },
    //     { value: 'UM', label: 'United States Minor Outlying Islands' },
    //     { value: 'UY', label: 'Uruguay' },
    //     { value: 'UZ', label: 'Uzbekistan' },
    //     { value: 'VU', label: 'Vanuatu' },
    //     { value: 'VE', label: 'Venezuela, Bolivarian Republic of' },
    //     { value: 'VN', label: 'Viet Nam' },
    //     { value: 'VG', label: 'Virgin Islands, British' },
    //     { value: 'VI', label: 'Virgin Islands, U.S.' },
    //     { value: 'WF', label: 'Wallis and Futuna' },
    //     { value: 'EH', label: 'Western Sahara' },
    //     { value: 'YE', label: 'Yemen' },
    //     { value: 'ZM', label: 'Zambia' },
    //     { value: 'ZW', label: 'Zimbabwe' },
    //   ];

    const countries = [
      { value: "AF", label: "Afghanistan", code: "+93" },
      { value: "AX", label: "Åland Islands", code: "+358" },
      { value: "AL", label: "Albania", code: "+355" },
      { value: "DZ", label: "Algeria", code: "+213" },
      { value: "AS", label: "American Samoa", code: "+1-684" },
      { value: "AD", label: "Andorra", code: "+376" },
      { value: "AO", label: "Angola", code: "+244" },
      { value: "AI", label: "Anguilla", code: "+1-264" },
      { value: "AQ", label: "Antarctica", code: "+672" },
      { value: "AG", label: "Antigua and Barbuda", code: "+1-268" },
      { value: "AR", label: "Argentina", code: "+54" },
      { value: "AM", label: "Armenia", code: "+374" },
      { value: "AW", label: "Aruba", code: "+297" },
      { value: "AU", label: "Australia", code: "+61" },
      { value: "AT", label: "Austria", code: "+43" },
      { value: "AZ", label: "Azerbaijan", code: "+994" },
      { value: "BS", label: "Bahamas", code: "+1-242" },
      { value: "BH", label: "Bahrain", code: "+973" },
      { value: "BD", label: "Bangladesh", code: "+880" },
      { value: "BB", label: "Barbados", code: "+1-246" },
      { value: "BY", label: "Belarus", code: "+375" },
      { value: "BE", label: "Belgium", code: "+32" },
      { value: "BZ", label: "Belize", code: "+501" },
      { value: "BJ", label: "Benin", code: "+229" },
      { value: "BM", label: "Bermuda", code: "+1-441" },
      { value: "BT", label: "Bhutan", code: "+975" },
      { value: "BO", label: "Bolivia, Plurinational State of", code: "+591" },
      { value: "BQ", label: "Bonaire, Sint Eustatius and Saba", code: "+599" },
      { value: "BA", label: "Bosnia and Herzegovina", code: "+387" },
      { value: "BW", label: "Botswana", code: "+267" },
      { value: "BV", label: "Bouvet Island", code: "+47" },
      { value: "BR", label: "Brazil", code: "+55" },
      { value: "IO", label: "British Indian Ocean Territory", code: "+246" },
      { value: "BN", label: "Brunei Darussalam", code: "+673" },
      { value: "BG", label: "Bulgaria", code: "+359" },
      { value: "BF", label: "Burkina Faso", code: "+226" },
      { value: "BI", label: "Burundi", code: "+257" },
      { value: "KH", label: "Cambodia", code: "+855" },
      { value: "CM", label: "Cameroon", code: "+237" },
      { value: "CA", label: "Canada", code: "+1" },
      { value: "CV", label: "Cape Verde", code: "+238" },
      { value: "KY", label: "Cayman Islands", code: "+1-345" },
      { value: "CF", label: "Central African Republic", code: "+236" },
      { value: "TD", label: "Chad", code: "+235" },
      { value: "CL", label: "Chile", code: "+56" },
      { value: "CN", label: "China", code: "+86" },
      { value: "CX", label: "Christmas Island", code: "+61" },
      { value: "CC", label: "Cocos (Keeling) Islands", code: "+61" },
      { value: "CO", label: "Colombia", code: "+57" },
      { value: "KM", label: "Comoros", code: "+269" },
      { value: "CG", label: "Congo", code: "+242" },
      {
        value: "CD",
        label: "Congo, the Democratic Republic of the",
        code: "+243",
      },
      { value: "CK", label: "Cook Islands", code: "+682" },
      { value: "CR", label: "Costa Rica", code: "+506" },
      { value: "CI", label: "Côte d'Ivoire", code: "+225" },
      { value: "HR", label: "Croatia", code: "+385" },
      { value: "CU", label: "Cuba", code: "+53" },
      { value: "CW", label: "Curaçao", code: "+599" },
      { value: "CY", label: "Cyprus", code: "+357" },
      { value: "CZ", label: "Czech Republic", code: "+420" },
      { value: "DK", label: "Denmark", code: "+45" },
      { value: "DJ", label: "Djibouti", code: "+253" },
      { value: "DM", label: "Dominica", code: "+1-767" },
      {
        value: "DO",
        label: "Dominican Republic",
        code: "+1-809, +1-829, +1-849",
      },
      { value: "EC", label: "Ecuador", code: "+593" },
      { value: "EG", label: "Egypt", code: "+20" },
      { value: "SV", label: "El Salvador", code: "+503" },
      { value: "GQ", label: "Equatorial Guinea", code: "+240" },
      { value: "ER", label: "Eritrea", code: "+291" },
      { value: "EE", label: "Estonia", code: "+372" },
      { value: "ET", label: "Ethiopia", code: "+251" },
      { value: "FK", label: "Falkland Islands (Malvinas)", code: "+500" },
      { value: "FO", label: "Faroe Islands", code: "+298" },
      { value: "FJ", label: "Fiji", code: "+679" },
      { value: "FI", label: "Finland", code: "+358" },
      { value: "FR", label: "France", code: "+33" },
      { value: "GF", label: "French Guiana", code: "+594" },
      { value: "PF", label: "French Polynesia", code: "+689" },
      { value: "TF", label: "French Southern Territories", code: "+262" },
      { value: "GA", label: "Gabon", code: "+241" },
      { value: "GM", label: "Gambia", code: "+220" },
      { value: "GE", label: "Georgia", code: "+995" },
      { value: "DE", label: "Germany", code: "+49" },
      { value: "GH", label: "Ghana", code: "+233" },
      { value: "GI", label: "Gibraltar", code: "+350" },
      { value: "GR", label: "Greece", code: "+30" },
      { value: "GL", label: "Greenland", code: "+299" },
      { value: "GD", label: "Grenada", code: "+1-473" },
      { value: "GP", label: "Guadeloupe", code: "+590" },
      { value: "GU", label: "Guam", code: "+1-671" },
      { value: "GT", label: "Guatemala", code: "+502" },
      { value: "GG", label: "Guernsey", code: "+44-1481" },
      { value: "GW", label: "Guinea-Bissau", code: "+245" },
      { value: "GY", label: "Guyana", code: "+592" },
      { value: "HT", label: "Haiti", code: "+509" },
      { value: "HM", label: "Heard Island and McDonald Islands", code: "+672" },
      { value: "VA", label: "Holy See (Vatican City State)", code: "+379" },
      { value: "HN", label: "Honduras", code: "+504" },
      { value: "HK", label: "Hong Kong", code: "+852" },
      { value: "HU", label: "Hungary", code: "+36" },
      { value: "IS", label: "Iceland", code: "+354" },
      { value: "IN", label: "India", code: "+91" },
      { value: "ID", label: "Indonesia", code: "+62" },
      { value: "IR", label: "Iran, Islamic Republic of", code: "+98" },
      { value: "IQ", label: "Iraq", code: "+964" },
      { value: "IE", label: "Ireland", code: "+353" },
      { value: "IM", label: "Isle of Man", code: "+44-1624" },
      { value: "IL", label: "Israel", code: "+972" },
      { value: "IT", label: "Italy", code: "+39" },
      { value: "JM", label: "Jamaica", code: "+1-876" },
      { value: "JP", label: "Japan", code: "+81" },
      { value: "JE", label: "Jersey", code: "+44-1534" },
      { value: "JO", label: "Jordan", code: "+962" },
      { value: "KZ", label: "Kazakhstan", code: "+7" },
      { value: "KE", label: "Kenya", code: "+254" },
      { value: "KI", label: "Kiribati", code: "+686" },
      {
        value: "KP",
        label: "Korea, Democratic People's Republic of",
        code: "+850",
      },
      { value: "KR", label: "Korea, Republic of", code: "+82" },
      { value: "KW", label: "Kuwait", code: "+965" },
      { value: "KG", label: "Kyrgyzstan", code: "+996" },
      { value: "LA", label: "Lao People's Democratic Republic", code: "+856" },
      { value: "LV", label: "Latvia", code: "+371" },
      { value: "LB", label: "Lebanon", code: "+961" },
      { value: "LS", label: "Lesotho", code: "+266" },
      { value: "LR", label: "Liberia", code: "+231" },
      { value: "LY", label: "Libya", code: "+218" },
      { value: "LI", label: "Liechtenstein", code: "+423" },
      { value: "LT", label: "Lithuania", code: "+370" },
      { value: "LU", label: "Luxembourg", code: "+352" },
      { value: "MO", label: "Macao", code: "+853" },
      {
        value: "MK",
        label: "Macedonia, the former Yugoslav Republic of",
        code: "+389",
      },
      { value: "MG", label: "Madagascar", code: "+261" },
      { value: "MW", label: "Malawi", code: "+265" },
      { value: "MY", label: "Malaysia", code: "+60" },
      { value: "MV", label: "Maldives", code: "+960" },
      { value: "ML", label: "Mali", code: "+223" },
      { value: "MT", label: "Malta", code: "+356" },
      { value: "MH", label: "Marshall Islands", code: "+692" },
      { value: "MQ", label: "Martinique", code: "+596" },
      { value: "MR", label: "Mauritania", code: "+222" },
      { value: "MU", label: "Mauritius", code: "+230" },
      { value: "YT", label: "Mayotte", code: "+262" },
      { value: "MX", label: "Mexico", code: "+52" },
      { value: "FM", label: "Micronesia, Federated States of", code: "+691" },
      { value: "MD", label: "Moldova, Republic of", code: "+373" },
      { value: "MC", label: "Monaco", code: "+377" },
      { value: "MN", label: "Mongolia", code: "+976" },
      { value: "ME", label: "Montenegro", code: "+382" },
      { value: "MS", label: "Montserrat", code: "+1-664" },
      { value: "MA", label: "Morocco", code: "+212" },
      { value: "MZ", label: "Mozambique", code: "+258" },
      { value: "MM", label: "Myanmar", code: "+95" },
      { value: "NA", label: "Namibia", code: "+264" },
      { value: "NR", label: "Nauru", code: "+674" },
      { value: "NP", label: "Nepal", code: "+977" },
      { value: "NL", label: "Netherlands", code: "+31" },
      { value: "NC", label: "New Caledonia", code: "+687" },
      { value: "NZ", label: "New Zealand", code: "+64" },
      { value: "NI", label: "Nicaragua", code: "+505" },
      { value: "NE", label: "Niger", code: "+227" },
      { value: "NG", label: "Nigeria", code: "+234" },
      { value: "NU", label: "Niue", code: "+683" },
      { value: "NF", label: "Norfolk Island", code: "+672" },
      { value: "MP", label: "Northern Mariana Islands", code: "+1-670" },
      { value: "NO", label: "Norway", code: "+47" },
      { value: "OM", label: "Oman", code: "+968" },
      { value: "PK", label: "Pakistan", code: "+92" },
      { value: "PW", label: "Palau", code: "+680" },
      { value: "PS", label: "Palestine, State of", code: "+970" },
      { value: "PA", label: "Panama", code: "+507" },
      { value: "PG", label: "Papua New Guinea", code: "+675" },
      { value: "PY", label: "Paraguay", code: "+595" },
      { value: "PE", label: "Peru", code: "+51" },
      { value: "PH", label: "Philippines", code: "+63" },
      { value: "PN", label: "Pitcairn", code: "+64" },
      { value: "PL", label: "Poland", code: "+48" },
      { value: "PT", label: "Portugal", code: "+351" },
      { value: "PR", label: "Puerto Rico", code: "+1-787, +1-939" },
      { value: "QA", label: "Qatar", code: "+974" },
      { value: "RE", label: "Réunion", code: "+262" },
      { value: "RO", label: "Romania", code: "+40" },
      { value: "RU", label: "Russian Federation", code: "+7" },
      { value: "RW", label: "Rwanda", code: "+250" },
      { value: "BL", label: "Saint Barthélemy", code: "+590" },
      {
        value: "SH",
        label: "Saint Helena, Ascension and Tristan da Cunha",
        code: "+290",
      },
      { value: "KN", label: "Saint Kitts and Nevis", code: "+1-869" },
      { value: "LC", label: "Saint Lucia", code: "+1-758" },
      { value: "MF", label: "Saint Martin (French part)", code: "+590" },
      { value: "PM", label: "Saint Pierre and Miquelon", code: "+508" },
      {
        value: "VC",
        label: "Saint Vincent and the Grenadines",
        code: "+1-784",
      },
      { value: "WS", label: "Samoa", code: "+685" },
      { value: "SM", label: "San Marino", code: "+378" },
      { value: "ST", label: "Sao Tome and Principe", code: "+239" },
      { value: "SA", label: "Saudi Arabia", code: "+966" },
      { value: "SN", label: "Senegal", code: "+221" },
      { value: "RS", label: "Serbia", code: "+381" },
      { value: "SC", label: "Seychelles", code: "+248" },
      { value: "SL", label: "Sierra Leone", code: "+232" },
      { value: "SG", label: "Singapore", code: "+65" },
      { value: "SX", label: "Sint Maarten (Dutch part)", code: "+1-721" },
      { value: "SK", label: "Slovakia", code: "+421" },
      { value: "SI", label: "Slovenia", code: "+386" },
      { value: "SB", label: "Solomon Islands", code: "+677" },
      { value: "SO", label: "Somalia", code: "+252" },
      { value: "ZA", label: "South Africa", code: "+27" },
      {
        value: "GS",
        label: "South Georgia and the South Sandwich Islands",
        code: "+500",
      },
      { value: "SS", label: "South Sudan", code: "+211" },
      { value: "ES", label: "Spain", code: "+34" },
      { value: "LK", label: "Sri Lanka", code: "+94" },
      { value: "SD", label: "Sudan", code: "+249" },
      { value: "SR", label: "Suriname", code: "+597" },
      { value: "SJ", label: "Svalbard and Jan Mayen", code: "+47" },
      { value: "SZ", label: "Eswatini", code: "+268" },
      { value: "SE", label: "Sweden", code: "+46" },
      { value: "CH", label: "Switzerland", code: "+41" },
      { value: "SY", label: "Syrian Arab Republic", code: "+963" },
      { value: "TW", label: "Taiwan, Province of China", code: "+886" },
      { value: "TJ", label: "Tajikistan", code: "+992" },
      { value: "TZ", label: "Tanzania, United Republic of", code: "+255" },
      { value: "TH", label: "Thailand", code: "+66" },
      { value: "TL", label: "Timor-Leste", code: "+670" },
      { value: "TG", label: "Togo", code: "+228" },
      { value: "TK", label: "Tokelau", code: "+690" },
      { value: "TO", label: "Tonga", code: "+676" },
      { value: "TT", label: "Trinidad and Tobago", code: "+1-868" },
      { value: "TN", label: "Tunisia", code: "+216" },
      { value: "TR", label: "Turkey", code: "+90" },
      { value: "TM", label: "Turkmenistan", code: "+993" },
      { value: "TC", label: "Turks and Caicos Islands", code: "+1-649" },
      { value: "TV", label: "Tuvalu", code: "+688" },
      { value: "UG", label: "Uganda", code: "+256" },
      { value: "UA", label: "Ukraine", code: "+380" },
      { value: "AE", label: "United Arab Emirates", code: "+971" },
      { value: "GB", label: "United Kingdom", code: "+44" },
      { value: "US", label: "United States", code: "+1" },
      {
        value: "UM",
        label: "United States Minor Outlying Islands",
        code: "+1",
      },
      { value: "UY", label: "Uruguay", code: "+598" },
      { value: "UZ", label: "Uzbekistan", code: "+998" },
      { value: "VU", label: "Vanuatu", code: "+678" },
      { value: "VE", label: "Venezuela, Bolivarian Republic of", code: "+58" },
      { value: "VN", label: "Viet Nam", code: "+84" },
      { value: "VG", label: "Virgin Islands, British", code: "+1-284" },
      { value: "VI", label: "Virgin Islands, U.S.", code: "+1-340" },
      { value: "WF", label: "Wallis and Futuna", code: "+681" },
      { value: "EH", label: "Western Sahara", code: "+212" },
      { value: "YE", label: "Yemen", code: "+967" },
      { value: "ZM", label: "Zambia", code: "+260" },
      { value: "ZW", label: "Zimbabwe", code: "+263" },
    ];

    return countries;
  }
}

export default countries;
